package ok.automation.models.api.users.getCurrentUser;

import ok.automation.models.api.base.*;
import ok.automation.tech.extensions.BaseModel;

public class UsersGetCurrentUserResponse extends BaseModel {
    public Boolean accessible;
    public Integer age;
    public Boolean allows_anonym_access;
    public Boolean allows_messaging_only_for_friends;
    public String birthday;
    public Boolean birthdaySet;
    public Boolean blocked;
    public Boolean blocks;
    public Boolean can_vcall;
    public Boolean can_vmail;
    public String capabilities;
    public String city_of_birth;
    public Integer common_friends_count;
    public CurrentLocation current_location;
    public String current_status;
    public String current_status_date; // TODO orig: Date current_status_date
    public Long current_status_date_ms;
    public String current_status_id;
    public CurrentStatusMood current_status_mood;
    public String current_status_track_id;
    public String email;
    public Boolean feed_subscription;
    public String first_name;
    public Boolean forbids_mentioning;
    public Boolean friend;
    public Boolean friend_invitation;
    public String gender;
    public Boolean has_email;
    public Boolean has_phone;
    public Boolean has_service_invisible;
    public Boolean invited_by_friend;
    public String last_name;
    public String last_online;
    public Long last_online_ms;
    public String locale;
    public Location location;
    public Location location_of_birth;
    public String login;
    public String mobile;
    public Long modified_ms;
    public String name;
    public Boolean notifications_subscription;
    public String online;
    public String photo_id;
    public String pic1024x768;
    public String pic128max;
    public String pic128x128;
    public String pic180min;
    public String pic190x190;
    public String pic224x224;
    public String pic240min;
    public String pic288x288;
    public String pic320min;
    public String pic50x50;
    public String pic600x600;
    public String pic640x480;
    public String pic_1;
    public String pic_2;
    public String pic_3;
    public String pic_4;
    public String pic_5;
    public String pic_base;
    public String pic_full;
    public String pic_max;
    public Boolean premium;
    public Present[] presents;
    public Boolean privatE;// TODO orig: private
    public String ref;
    public String registered_date; // TODO orig: Date registered_date
    public Long registered_date_ms;
    public Relation[] relations;
    public Relationship relationship;
    public Boolean show_lock;
    public Status status;
    public String uid;
    public String url_chat;
    public String url_chat_mobile;
    public String url_profile;
    public String url_profile_mobile;
    public Boolean vip;
}
