package ok.automation.models.api.base;

public class MainPhoto {
    public String album_id;
    public Attrs attrs;
    public String author_name;
    public String author_ref;
    public String author_type;
    public String context;
    public Boolean copyable;
    public Long created_ms;
    public Short crop_size;
    public Short crop_x;
    public Short crop_y;
    public DiscussionSummary discussion_summary;
    public String group_id;
    public String id;
    public LikeSummary like_summary;
    public String moderation_status;
    public String owner_ref;
    public String pic1024max;
    public String pic1024x768;
    public String pic128max;
    public String pic128x128;
    public String pic160x120;
    public String pic176x176;
    public String pic180min;
    public String pic190x190;
    public String pic240min;
    public String pic320min;
    public String pic50x50;
    public String pic640x480;
    public String pic_base;
    public String pic_max;
    public String picgif;
    public String picmp4;
    public String picwebm;
    public String preview;
    public String ref;
    public ReshareSummary reshare_summary;
    public Byte rotations_angle;
    public Short standard_height;
    public Short standard_width;
    public String text;
    public String topic_id;
    public String type;
    public String user_id;
}
